multiplication_task:
  description: >
    mutliply the numbers {number1} and {number2} together accurately.
  expected_output: >
    the result of the multiplication as a string showing the input numbers and the result
  agent: multiplication_agent

addition_task:
  description: >
    add numbers {number1} and {number2} together accurately.
  expected_output: >
    The result of the addition as a string showing the input numbers and the result
  agent: addition_agent

reporting_task:
  description: >
    Review the results from the maths operations and report the 
    results of the calculations.
  expected_output: >
    A clear and accurate report of the calculation results
  agent: reporting_agent
